### ISSUE TITLE
Cache flutter in CI circle.

### ISSUE THREAD

**Issue by esron** [esron/systranca_app#13]
The CI circle is taking 3 minutes in most cases, this could be shortened if we manage to cache the flutter installation on Travis cache.

https://docs.travis-ci.com/user/speeding-up-the-build/#caching-the-dependencies

**Comment by mannprerak2** [comment]
Made a PR #14 which caches flutter installation

**Comment by esron** [comment]
It's done, thank you @mannprerak2 :+1:
