### ISSUE TITLE
Update to the newest version of flutter.

### ISSUE THREAD

**Issue by esron** [esron/systranca_app#23]
The project has been stopped for some time now and is not compatible with the newest flutter anymore.

**Comment by esron** [comment]
You can follow this guide: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by CoderNamedHendrick** [comment]
I would like to fix this issue, can I get it assigned to me😀😀

**Comment by esron** [comment]
@CoderNamedHendrick  You're on it. Thanks for the help.

**Comment by esron** [comment]
@CoderNamedHendrick Hey man, do you still have interest on working on this?

**Comment by esron** [comment]
This was recently solved.
